Add NFC Copy Cat
ElectronicCats/Arduino_Boards_Index pull request #14
Opened 2019-08-16 21:58 UTC by sabas1080

Hi @wero1414 

Add please the new board NFC Copy Cat "NFCat" for Arduino IDE, work of @juan-eduardo 

Thanks

2019-08-18 04:21 UTC, wero1414 commented on electroniccats/samd/boards.txt
> +electroniccats_nfc_copy_cat.pid.1=0xBAB7
Cambiar los PID de PID codes

2019-08-18 04:23 UTC, wero1414 requested changes
Cambiar PID, de preferencia ir cambiando variant.cpp a el variant ordenado

2019-08-18 04:23 UTC, wero1414 commented on electroniccats/samd/variants/nfc_copy_cat/variant.cpp
> +const PinDescription g_APinDescription[]=
No se uso el template de pines acomodados donde coincide el PA con el numero de pin

2019-08-19 16:52 UTC, sabas1080 commented on electroniccats/samd/boards.txt
> +electroniccats_nfc_copy_cat.pid.1=0xBAB7
Son los PID de PidCodes

2019-08-19 16:52 UTC, sabas1080 commented on electroniccats/samd/variants/nfc_copy_cat/variant.cpp
> +const PinDescription g_APinDescription[]=
Cual era la tarjeta de ejemplo?

2019-08-19 17:07 UTC, wero1414 commented on electroniccats/samd/variants/nfc_copy_cat/variant.cpp
> +const PinDescription g_APinDescription[]=
tracker

2019-08-26 19:07 UTC, wero1414 approved these changes

2019-08-26 19:07 UTC, merged

2019-08-26 19:12 UTC, sabas1080 commented
<3