feat(actions): Setup Github Actions for Release
ElectronicCats/Arduino_Boards_Index pull request #37
Opened 2024-03-25 18:42 UTC by JahazielLem

- Scripts:
  - get_files:
    - Download the release files
  - release.py:
    - Merge the index json file with the new release file
- Action for the remote triggering from the ArduinoCore-samd

2024-03-26 23:20 UTC, sabas1080 requested changes

2024-03-26 23:20 UTC, sabas1080 commented on tools/get_files.sh
> +wget https://github.com/JahazielLem/ArduinoCore-samd/releases/download/$tag_version/$package_name
El link aun apunta a https://github.com/JahazielLem, debe cambiar

2024-03-26 23:20 UTC, sabas1080 commented on tools/get_files.sh
> +wget https://github.com/JahazielLem/ArduinoCore-samd/releases/download/$tag_version/$package_json
El link aun apunta a https://github.com/JahazielLem, debe cambiar

2024-03-27 01:25 UTC, JahazielLem commented on tools/get_files.sh
> +wget https://github.com/JahazielLem/ArduinoCore-samd/releases/download/$tag_version/$package_json
Listo, se cambiaron cuando hice la prueba de la presentacion :P

2024-03-27 01:27 UTC, sabas1080 approved these changes
Ok para mi, deben estar los 3 review para release

2024-03-27 14:49 UTC, DeimosHall reviewed
LGTM

2024-03-27 14:49 UTC, DeimosHall commented on .github/workflows/main.yml
> +      - run: git add .
I'd change this to `git add -A` to include possible future changes outside `tools/`

2024-03-27 14:49 UTC, DeimosHall commented on .github/workflows/main.yml
> +      - run: git commit --message 'Release ${{ github.event.client_payload.tag}}'
Coventional commits bro!

2024-03-27 15:22 UTC, DeimosHall reviewed
Nice :)

2024-03-27 16:21 UTC, merged