add citizen board
ElectronicCats/Arduino_Boards_Index pull request #7
Opened 2019-03-19 23:19 UTC by chio7896

Buenas tardes,

Agrego la carpeta de CatWan Citizen. 

Saludos.

2019-03-20 01:36 UTC, sabas1080 requested changes

2019-03-20 01:36 UTC, sabas1080 commented on electroniccats/samd/variants/catwan_citizen/variant.h
> +extern SERCOM sercom4;
remover sercom4 y 5  que no se utilizan

2019-03-20 01:36 UTC, sabas1080 commented on electroniccats/samd/variants/catwan_citizen/variant.h
> +#define SERIAL_PORT_HARDWARE        Serial1
Serial1 no existe, remover por favor

2019-03-20 01:36 UTC, sabas1080 commented on electroniccats/samd/boards.txt
> +electroniccats_citizen_board.name=Electronic Cats CatWAN Citizen Board
propongo solo se llame "Electronic Cats CatWAN Citizen"

2019-03-20 01:37 UTC, sabas1080 commented
Agregar al .travis la tarjeta para pruebas unitarias por favor

2019-03-21 17:28 UTC, sabas1080 commented on electroniccats/samd/boards.txt
> +electroniccats_citizen_board.name=Electronic Cats CatWAN Citizen Board
Cambiaste el "usb_product", pero no el "name" @chio7896

2019-03-21 21:30 UTC, sabas1080 approved these changes

2019-03-25 16:12 UTC, sabas1080 commented
@wero1414 listo para merge si tu apruebas

2019-03-26 05:05 UTC, wero1414 approved these changes

2019-03-26 05:05 UTC, merged